### ISSUE TITLE
[Improvement] Major version 2.0.0

### ISSUE THREAD

**Issue by chouchouji** [Pana/nrm#207]
# Tasks

- [x] migrate to typescript
- [x] migrate to vitest
- [x] migrate to pnpm
- [x] use boime

**Comment by chouchouji** [comment]
@iosh Can you create a new branch for this issue? I will submit pr into that branch.

**Comment by chouchouji** [comment]
> > @iosh Can you create a new branch for this issue? I will submit pr into that branch.
> 
> The v2 branch is available.

Thanks.

**Comment by chouchouji** [comment]
Should we use pnpm to replace yarn?

**Comment by iosh** [comment]
> Should we use pnpm to replace yarn?

OK to me.

**Comment by chouchouji** [comment]
How about migrating to esm?

**Comment by iosh** [comment]
> How about migrating to esm?

I think we can use esm in source code ,but build it to Commonjs(or both) via Typescript, What do you think?

**Comment by iosh** [comment]
> use eslint

Try this https://biomejs.dev (It is like prettier + eslinet)

**Comment by chouchouji** [comment]
> > use eslint
> 
> Try this https://biomejs.dev (It is like prettier + eslinet)

Ok

**Comment by chouchouji** [comment]
> > How about migrating to esm?
> 
> I think we can use esm in source code ,but build it to Commonjs(or both) via Typescript, What do you think?

I think it is ok.

**Comment by iosh** [comment]
> @iosh I want to recommend a release tool https://github.com/varletjs/varlet-release is maintained by myself.
> 
> It is very easy to use. I think you will like it.

I have check your package, It is great,but i have use the changeset in my every package.

**Comment by chouchouji** [comment]
> > @iosh I want to recommend a release tool https://github.com/varletjs/varlet-release is maintained by myself.
> > It is very easy to use. I think you will like it.
> 
> I have check your package, It is great,but i have use the changeset in my every package.

OK, we should keep using it.

**Comment by chouchouji** [comment]
@iosh  I had completed these tasks. Can you update the ci test file?

**Comment by iosh** [comment]
> @iosh I had completed these tasks. Can you update the ci test file?

OK.

**Comment by chouchouji** [comment]
![image](https://github.com/user-attachments/assets/b6d0b51d-be9a-4e34-9c24-b6104bb1754a)

I think the type files are not necessary.

**Comment by iosh** [comment]
> ![image](https://private-user-images.githubusercontent.com/70570907/391387306-b6d0b51d-be9a-4e34-9c24-b6104bb1754a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMDU1MzYsIm5iZiI6MTczMzEwNTIzNiwicGF0aCI6Ii83MDU3MDkwNy8zOTEzODczMDYtYjZkMGI1MWQtYmU5YS00ZTM0LTljMjQtYjYxMDRiYjE3NTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDAyMDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NzBmMTUzYzI5NDY2MjhhYThmNzE3NDNlZmNiMGE0ZjFiZTY4NzQ3ZDg3ZjQzMWI1MjhhODU3MzgyZmFhZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6GOYBOH0C_M2Ht_lcOWp6dpTx65Ce7Zl_hIOb9x5_bs)
> 
> I think the type files are not necessary.

You are right. The type files not necessary.

**Comment by chouchouji** [comment]
@iosh  Do you meet this problem? 

![image](https://github.com/user-attachments/assets/a4292fad-010b-4ae8-880a-2dcb2523f203)

**Comment by chouchouji** [comment]
> > ![image](https://private-user-images.githubusercontent.com/70570907/391387306-b6d0b51d-be9a-4e34-9c24-b6104bb1754a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMDU1MzYsIm5iZiI6MTczMzEwNTIzNiwicGF0aCI6Ii83MDU3MDkwNy8zOTEzODczMDYtYjZkMGI1MWQtYmU5YS00ZTM0LTljMjQtYjYxMDRiYjE3NTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDAyMDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NzBmMTUzYzI5NDY2MjhhYThmNzE3NDNlZmNiMGE0ZjFiZTY4NzQ3ZDg3ZjQzMWI1MjhhODU3MzgyZmFhZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6GOYBOH0C_M2Ht_lcOWp6dpTx65Ce7Zl_hIOb9x5_bs)
> > I think the type files are not necessary.
> 
> You are right. The type files not necessary.

The related pr is #210

**Comment by iosh** [comment]
> @iosh Do you meet this problem?
> 
> ![image](https://private-user-images.githubusercontent.com/70570907/391390865-a4292fad-010b-4ae8-880a-2dcb2523f203.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMDY4MzMsIm5iZiI6MTczMzEwNjUzMywicGF0aCI6Ii83MDU3MDkwNy8zOTEzOTA4NjUtYTQyOTJmYWQtMDEwYi00YWU4LTg4MGEtMmRjYjI1MjNmMjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDAyMjg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhN2Y5ZTc3Zjk4NjczZjcwOWEzYmY3MTFhZmU4OWQxN2U3YmYyMDEyNTM5ZGNhMjNiMTU1N2Q3NWI5ZDAwMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.StmTd2gOM3cNRni1CGlovUZ4U6CMRR2swHHIBoG2_n0)

Yes，try `npm link` to link current project to global, then try the nrm with command，you  can see the error.
Or I'll check it later.

**Comment by chouchouji** [comment]
![image](https://github.com/user-attachments/assets/f102a2ea-58c3-45b0-981a-20c3d6589fa1)
Thanks. It is useful.

**Comment by chouchouji** [comment]
![image](https://github.com/user-attachments/assets/e0fcd293-b0a5-4720-9b71-7480574a4dfb)

Should we update this test case? It looks like prompt difference.

**Comment by iosh** [comment]
> ![image](https://private-user-images.githubusercontent.com/70570907/391392723-e0fcd293-b0a5-4720-9b71-7480574a4dfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMDc0OTUsIm5iZiI6MTczMzEwNzE5NSwicGF0aCI6Ii83MDU3MDkwNy8zOTEzOTI3MjMtZTBmY2QyOTMtYjBhNS00NzIwLTliNzEtNzQ4MDU3NGE0ZGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDAyMzk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMzNiMjFkOThkZGZiMjFlZGZlODg0NzcwMTNhMTAxNTMzODEyZjYyZjU4MmY3OWE4NmI3MGI5NTczZGUwYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HqPMo__NHco1mtUjxgRZ9sw-l0tbTxDEDYiEiiMc9Mo)
> 
> Should we update this test case? It looks like prompt difference.

Just update this.

**Comment by chouchouji** [comment]
> > ![image](https://private-user-images.githubusercontent.com/70570907/391392723-e0fcd293-b0a5-4720-9b71-7480574a4dfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMDc0OTUsIm5iZiI6MTczMzEwNzE5NSwicGF0aCI6Ii83MDU3MDkwNy8zOTEzOTI3MjMtZTBmY2QyOTMtYjBhNS00NzIwLTliNzEtNzQ4MDU3NGE0ZGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDAyMzk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMzNiMjFkOThkZGZiMjFlZGZlODg0NzcwMTNhMTAxNTMzODEyZjYyZjU4MmY3OWE4NmI3MGI5NTczZGUwYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HqPMo__NHco1mtUjxgRZ9sw-l0tbTxDEDYiEiiMc9Mo)
> > Should we update this test case? It looks like prompt difference.
> 
> Just update this.

Done.

**Comment by chouchouji** [comment]
@iosh How about adding internal github registry `https://npm.pkg.github.com` after v2.0.0? I think it is easy to do.

**Comment by iosh** [comment]
> @iosh How about adding internal github registry `https://npm.pkg.github.com` after v2.0.0? I think it is easy to do.

Good, I haven't used it yet

**Comment by chouchouji** [comment]
> > @iosh How about adding internal github registry `https://npm.pkg.github.com` after v2.0.0? I think it is easy to do.
> 
> Good, I haven't used it yet

Me too. I use taobao and npm most of the time.  I see todo list includes this task and I read [https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry). In addition,  when will we release v2.0.0？

**Comment by iosh** [comment]
> > > @iosh How about adding internal github registry `https://npm.pkg.github.com` after v2.0.0? I think it is easy to do.
> > 
> > 
> > Good, I haven't used it yet
> 
> Me too. I use taobao and npm most of the time. I see todo list includes this task and I read https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry. In addition, when will we release v2.0.0？

Should we add support for the -local feature to the other commands before releasing version 2.0, or should we release version 2.0 first and then add the feature?

**Comment by chouchouji** [comment]
> > > > @iosh How about adding internal github registry `https://npm.pkg.github.com` after v2.0.0? I think it is easy to do.
> > > 
> > > 
> > > Good, I haven't used it yet
> > 
> > 
> > Me too. I use taobao and npm most of the time. I see todo list includes this task and I read https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry. In addition, when will we release v2.0.0？
> 
> Should we add support for the -local feature to the other commands before releasing version 2.0, or should we release version 2.0 first and then add the feature?

I think we should do it after releasing v2.0.0. We can add a issue to adapt to other commands by subtasks.

**Comment by iosh** [comment]
> > > > > @iosh How about adding internal github registry `https://npm.pkg.github.com` after v2.0.0? I think it is easy to do.
> > > > 
> > > > 
> > > > Good, I haven't used it yet
> > > 
> > > 
> > > Me too. I use taobao and npm most of the time. I see todo list includes this task and I read https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry. In addition, when will we release v2.0.0？
> > 
> > 
> > Should we add support for the -local feature to the other commands before releasing version 2.0, or should we release version 2.0 first and then add the feature?
> 
> I think we should do it after releasing v2.0.0. We can add a issue to adapt to other commands by subtasks.

OK , We'll check it over the weekend and then release version 2.0.

**Comment by chouchouji** [comment]
> > > > > > @iosh How about adding internal github registry `https://npm.pkg.github.com` after v2.0.0? I think it is easy to do.
> > > > > 
> > > > > 
> > > > > Good, I haven't used it yet
> > > > 
> > > > 
> > > > Me too. I use taobao and npm most of the time. I see todo list includes this task and I read https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry. In addition, when will we release v2.0.0？
> > > 
> > > 
> > > Should we add support for the -local feature to the other commands before releasing version 2.0, or should we release version 2.0 first and then add the feature?
> > 
> > 
> > I think we should do it after releasing v2.0.0. We can add a issue to adapt to other commands by subtasks.
> 
> OK , We'll check it over the weekend and then release version 2.0.

Thanks. I will add a issue about it. We should talk about the local option in detail before we are ready to do.

**Comment by chouchouji** [comment]
> > > > > > > @iosh How about adding internal github registry `https://npm.pkg.github.com` after v2.0.0? I think it is easy to do.
> > > > > > 
> > > > > > 
> > > > > > Good, I haven't used it yet
> > > > > 
> > > > > 
> > > > > Me too. I use taobao and npm most of the time. I see todo list includes this task and I read https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry. In addition, when will we release v2.0.0？
> > > > 
> > > > 
> > > > Should we add support for the -local feature to the other commands before releasing version 2.0, or should we release version 2.0 first and then add the feature?
> > > 
> > > 
> > > I think we should do it after releasing v2.0.0. We can add a issue to adapt to other commands by subtasks.
> > 
> > 
> > OK , We'll check it over the weekend and then release version 2.0.
> 
> Thanks. I will add a issue about it. We should talk about the local option in detail before we are ready to do.

Related issue is #211.
